//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DouStatistics.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeyWords()
        {
            this.ResultsSearch = new HashSet<ResultsSearch>();
        }
    
        public int Id { get; set; }
        public string KeyWord { get; set; }
        public Nullable<bool> IsCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultsSearch> ResultsSearch { get; set; }
    }
}
